chore: don't depend on godebug
We don't need to depend on this, so we shouldn't. The new error looks
this:
```
Error Trace:	/home/solomonjacobs/get/f-alertmanager/provider/mem/mem_test.go:224
Error:      	Received unexpected error:
                field `Labels` mismatch.
                 Expected: {bar="foo"}
                 Got: {bar="boo"}
                field `Annotations` mismatch.
                 Expected: {foo="bar"}
                 Got: {boo="bar"}
                field `UpdatedAt` mismatch.
                 Expected: 2025-11-22 20:48:30.75618754 +0100 CET m=+0.000942595
                 Got: 2025-11-22 20:48:30.85618754 +0100 CET m=+0.100942595
                field `Timeout` mismatch.
                 Expected: false
                 Got: true
```

Signed-off-by: Solomon Jacobs <solomonjacobs@protonmail.com>